import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f9fa' },
  progress: { padding: 20, backgroundColor: '#fff' },
  progressText: { fontSize: 14, color: '#666', marginBottom: 8 },
  progressBar: { height: 6, backgroundColor: '#e0e0e0', borderRadius: 3 },
  progressFill: { height: '100%', backgroundColor: '#667eea', borderRadius: 3 },
  scene: { padding: 20 },
  title: { fontSize: 20, fontWeight: 'bold', color: '#333', marginBottom: 15 },
  narration: { fontSize: 16, color: '#555', marginBottom: 15, lineHeight: 22 },
  sentenceBox: { backgroundColor: '#e8f4fd', padding: 15, borderRadius: 8, marginBottom: 15 },
  sentence: { fontSize: 18, fontWeight: '600', color: '#333', textAlign: 'center' },
  instruction: { fontSize: 14, color: '#666', marginBottom: 20, fontStyle: 'italic' },
  button: { backgroundColor: '#667eea', padding: 15, borderRadius: 8, alignItems: 'center' },
  buttonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  choices: { marginTop: 10 },
  choiceButton: { backgroundColor: '#fff', padding: 15, borderRadius: 8, marginBottom: 10, borderWidth: 1, borderColor: '#ddd' },
  choiceText: { fontSize: 14, color: '#333' },
  hint: { backgroundColor: '#fff3cd', padding: 15, borderRadius: 8, marginBottom: 15, borderWidth: 1, borderColor: '#ffeaa7' },
  hintText: { fontSize: 14, color: '#856404' },
  orText: { textAlign: 'center', fontSize: 16, fontWeight: 'bold', marginVertical: 15, color: '#666' },
  textInput: { backgroundColor: '#fff', padding: 15, borderRadius: 8, borderWidth: 1, borderColor: '#ddd', minHeight: 80, textAlignVertical: 'top' },
  matchingGame: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  column: { flex: 1, backgroundColor: '#f0f0f0', padding: 15, borderRadius: 8, marginHorizontal: 5 },
  columnTitle: { fontSize: 16, fontWeight: 'bold', textAlign: 'center', color: '#333' },
  draggableItem: { backgroundColor: '#fff', padding: 12, borderRadius: 8, marginBottom: 8, borderWidth: 1, borderColor: '#667eea' },
  itemText: { fontSize: 14, color: '#333', textAlign: 'center' },
  habitButton: { backgroundColor: '#fff', padding: 15, borderRadius: 8, marginBottom: 10, borderWidth: 2, borderColor: '#ddd' },
  selectedHabit: { borderColor: '#667eea', backgroundColor: '#f0f4ff' },
  habitText: { fontSize: 14, color: '#333' },
  selectedHabitText: { color: '#667eea', fontWeight: '600' },
  disabledButton: { backgroundColor: '#ccc' },
  completionContainer: { alignItems: 'center', paddingVertical: 40 },
  badge: { fontSize: 80, marginBottom: 20 },
  completionTitle: { fontSize: 28, fontWeight: 'bold', color: '#333', marginBottom: 20, textAlign: 'center' },
  completionText: { fontSize: 16, color: '#555', textAlign: 'center', marginBottom: 15, lineHeight: 22 },
  buttonContainer: { width: '100%', marginTop: 30 },
  primaryButton: { backgroundColor: '#667eea', padding: 15, borderRadius: 8, alignItems: 'center', marginBottom: 15 }
});