-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg8FvUf4Zr23cJTQp+
tzbTAeyfm+kvYel/3J+qf7ld6bWgCgYIKoZIzj0DAQehRANCAAQ8WIi8yQhHuvAk
sADN5W0G/UqkqmEgpGb1uA+XdwmpeQA2/DuGz9Bes25ZJPnPnTQDda4jKBK4fH+1
RRHsQ1cl
-----END PRIVATE KEY-----